<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260923113625 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the initial relational database schema for Vite & Gourmand';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE allergen (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_25BF08CE5E237E06 ON allergen (name)');
        $this->addSql('CREATE TABLE app_user (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, phone VARCHAR(20) NOT NULL, postal_address VARCHAR(255) NOT NULL, postal_code VARCHAR(10) NOT NULL, city VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE TABLE customer_order (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, people_count INT NOT NULL, delivery_address VARCHAR(255) NOT NULL, delivery_postal_code VARCHAR(10) NOT NULL, delivery_city VARCHAR(100) NOT NULL, delivery_date DATE NOT NULL, delivery_time TIME(0) WITHOUT TIME ZONE NOT NULL, menu_amount_cents INT NOT NULL, discount_amount_cents INT NOT NULL, delivery_amount_cents INT NOT NULL, total_amount_cents INT NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, menu_id BIGINT NOT NULL, user_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3B1CE6A3CCD7E912 ON customer_order (menu_id)');
        $this->addSql('CREATE INDEX IDX_3B1CE6A3A76ED395 ON customer_order (user_id)');
        $this->addSql('CREATE TABLE dish (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, description TEXT DEFAULT NULL, course_type VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE dish_allergen (dish_id BIGINT NOT NULL, allergen_id BIGINT NOT NULL, PRIMARY KEY (dish_id, allergen_id))');
        $this->addSql('CREATE INDEX IDX_3C4389A5148EB0CB ON dish_allergen (dish_id)');
        $this->addSql('CREATE INDEX IDX_3C4389A56E775A4A ON dish_allergen (allergen_id)');
        $this->addSql('CREATE TABLE menu (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(150) NOT NULL, description TEXT NOT NULL, conditions TEXT NOT NULL, minimum_people INT NOT NULL, base_price_cents INT NOT NULL, available_stock INT NOT NULL, theme VARCHAR(50) NOT NULL, diet VARCHAR(50) NOT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE menu_dish (menu_id BIGINT NOT NULL, dish_id BIGINT NOT NULL, PRIMARY KEY (menu_id, dish_id))');
        $this->addSql('CREATE INDEX IDX_5D327CF6CCD7E912 ON menu_dish (menu_id)');
        $this->addSql('CREATE INDEX IDX_5D327CF6148EB0CB ON menu_dish (dish_id)');
        $this->addSql('CREATE TABLE menu_image (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, alt_text VARCHAR(255) NOT NULL, position INT NOT NULL, menu_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_54912738CCD7E912 ON menu_image (menu_id)');
        $this->addSql('CREATE TABLE opening_hour (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, day_of_week SMALLINT NOT NULL, morning_open TIME(0) WITHOUT TIME ZONE DEFAULT NULL, morning_close TIME(0) WITHOUT TIME ZONE DEFAULT NULL, afternoon_open TIME(0) WITHOUT TIME ZONE DEFAULT NULL, afternoon_close TIME(0) WITHOUT TIME ZONE DEFAULT NULL, is_closed BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_969BD7656A79171 ON opening_hour (day_of_week)');
        $this->addSql('CREATE TABLE order_contact_log (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contact_method VARCHAR(50) NOT NULL, reason TEXT NOT NULL, contacted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_id BIGINT NOT NULL, employee_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_69B7767B8D9F6D38 ON order_contact_log (order_id)');
        $this->addSql('CREATE INDEX IDX_69B7767B8C03F15C ON order_contact_log (employee_id)');
        $this->addSql('CREATE TABLE order_status_history (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_id BIGINT NOT NULL, changed_by_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_471AD77E8D9F6D38 ON order_status_history (order_id)');
        $this->addSql('CREATE INDEX IDX_471AD77E828AD0A0 ON order_status_history (changed_by_id)');
        $this->addSql('CREATE TABLE review (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating INT NOT NULL, comment TEXT NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, validated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, order_id BIGINT NOT NULL, user_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_794381C68D9F6D38 ON review (order_id)');
        $this->addSql('CREATE INDEX IDX_794381C6A76ED395 ON review (user_id)');
        $this->addSql('ALTER TABLE customer_order ADD CONSTRAINT FK_3B1CE6A3CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer_order ADD CONSTRAINT FK_3B1CE6A3A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dish_allergen ADD CONSTRAINT FK_3C4389A5148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dish_allergen ADD CONSTRAINT FK_3C4389A56E775A4A FOREIGN KEY (allergen_id) REFERENCES allergen (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_dish ADD CONSTRAINT FK_5D327CF6CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_dish ADD CONSTRAINT FK_5D327CF6148EB0CB FOREIGN KEY (dish_id) REFERENCES dish (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE menu_image ADD CONSTRAINT FK_54912738CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_contact_log ADD CONSTRAINT FK_69B7767B8D9F6D38 FOREIGN KEY (order_id) REFERENCES customer_order (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_contact_log ADD CONSTRAINT FK_69B7767B8C03F15C FOREIGN KEY (employee_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_status_history ADD CONSTRAINT FK_471AD77E8D9F6D38 FOREIGN KEY (order_id) REFERENCES customer_order (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_status_history ADD CONSTRAINT FK_471AD77E828AD0A0 FOREIGN KEY (changed_by_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C68D9F6D38 FOREIGN KEY (order_id) REFERENCES customer_order (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE review ADD CONSTRAINT FK_794381C6A76ED395 FOREIGN KEY (user_id) REFERENCES app_user (id) NOT DEFERRABLE');
        // Database-level defaults
        $this->addSql("ALTER TABLE app_user ALTER COLUMN is_active SET DEFAULT TRUE");
        $this->addSql("ALTER TABLE app_user ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP");
        $this->addSql("ALTER TABLE app_user ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP");

        $this->addSql("ALTER TABLE menu ALTER COLUMN available_stock SET DEFAULT 0");
        $this->addSql("ALTER TABLE menu ALTER COLUMN is_active SET DEFAULT TRUE");
        $this->addSql("ALTER TABLE menu ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP");
        $this->addSql("ALTER TABLE menu ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP");

        $this->addSql("ALTER TABLE customer_order ALTER COLUMN discount_amount_cents SET DEFAULT 0");
        $this->addSql("ALTER TABLE customer_order ALTER COLUMN delivery_amount_cents SET DEFAULT 0");
        $this->addSql("ALTER TABLE customer_order ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP");
        $this->addSql("ALTER TABLE customer_order ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP");

        $this->addSql("ALTER TABLE menu_image ALTER COLUMN position SET DEFAULT 0");

        $this->addSql("ALTER TABLE dish ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP");
        $this->addSql("ALTER TABLE dish ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP");

        $this->addSql("ALTER TABLE order_status_history ALTER COLUMN changed_at SET DEFAULT CURRENT_TIMESTAMP");
        $this->addSql("ALTER TABLE order_contact_log ALTER COLUMN contacted_at SET DEFAULT CURRENT_TIMESTAMP");

        $this->addSql("ALTER TABLE review ALTER COLUMN status SET DEFAULT 'pending'");
        $this->addSql("ALTER TABLE review ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP");

        $this->addSql("ALTER TABLE opening_hour ALTER COLUMN is_closed SET DEFAULT FALSE");

        // Database-level integrity constraints
        $this->addSql("ALTER TABLE menu ADD CONSTRAINT chk_menu_minimum_people CHECK (minimum_people > 0)");
        $this->addSql("ALTER TABLE menu ADD CONSTRAINT chk_menu_base_price CHECK (base_price_cents >= 0)");
        $this->addSql("ALTER TABLE menu ADD CONSTRAINT chk_menu_available_stock CHECK (available_stock >= 0)");

        $this->addSql("ALTER TABLE customer_order ADD CONSTRAINT chk_customer_order_people CHECK (people_count > 0)");
        $this->addSql("ALTER TABLE customer_order ADD CONSTRAINT chk_customer_order_menu_amount CHECK (menu_amount_cents >= 0)");
        $this->addSql("ALTER TABLE customer_order ADD CONSTRAINT chk_customer_order_discount CHECK (discount_amount_cents >= 0)");
        $this->addSql("ALTER TABLE customer_order ADD CONSTRAINT chk_customer_order_delivery_amount CHECK (delivery_amount_cents >= 0)");
        $this->addSql("ALTER TABLE customer_order ADD CONSTRAINT chk_customer_order_total CHECK (total_amount_cents >= 0)");

        $this->addSql("ALTER TABLE menu_image ADD CONSTRAINT chk_menu_image_position CHECK (position >= 0)");

        $this->addSql("ALTER TABLE review ADD CONSTRAINT chk_review_rating CHECK (rating BETWEEN 1 AND 5)");

        $this->addSql("ALTER TABLE opening_hour ADD CONSTRAINT chk_opening_hour_day CHECK (day_of_week BETWEEN 1 AND 7)");
        $this->addSql("ALTER TABLE opening_hour ADD CONSTRAINT chk_opening_hour_morning CHECK (morning_open IS NULL OR morning_close IS NULL OR morning_open < morning_close)");
        $this->addSql("ALTER TABLE opening_hour ADD CONSTRAINT chk_opening_hour_afternoon CHECK (afternoon_open IS NULL OR afternoon_close IS NULL OR afternoon_open < afternoon_close)");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE customer_order DROP CONSTRAINT FK_3B1CE6A3CCD7E912');
        $this->addSql('ALTER TABLE customer_order DROP CONSTRAINT FK_3B1CE6A3A76ED395');
        $this->addSql('ALTER TABLE dish_allergen DROP CONSTRAINT FK_3C4389A5148EB0CB');
        $this->addSql('ALTER TABLE dish_allergen DROP CONSTRAINT FK_3C4389A56E775A4A');
        $this->addSql('ALTER TABLE menu_dish DROP CONSTRAINT FK_5D327CF6CCD7E912');
        $this->addSql('ALTER TABLE menu_dish DROP CONSTRAINT FK_5D327CF6148EB0CB');
        $this->addSql('ALTER TABLE menu_image DROP CONSTRAINT FK_54912738CCD7E912');
        $this->addSql('ALTER TABLE order_contact_log DROP CONSTRAINT FK_69B7767B8D9F6D38');
        $this->addSql('ALTER TABLE order_contact_log DROP CONSTRAINT FK_69B7767B8C03F15C');
        $this->addSql('ALTER TABLE order_status_history DROP CONSTRAINT FK_471AD77E8D9F6D38');
        $this->addSql('ALTER TABLE order_status_history DROP CONSTRAINT FK_471AD77E828AD0A0');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C68D9F6D38');
        $this->addSql('ALTER TABLE review DROP CONSTRAINT FK_794381C6A76ED395');
        $this->addSql('DROP TABLE allergen');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE customer_order');
        $this->addSql('DROP TABLE dish');
        $this->addSql('DROP TABLE dish_allergen');
        $this->addSql('DROP TABLE menu');
        $this->addSql('DROP TABLE menu_dish');
        $this->addSql('DROP TABLE menu_image');
        $this->addSql('DROP TABLE opening_hour');
        $this->addSql('DROP TABLE order_contact_log');
        $this->addSql('DROP TABLE order_status_history');
        $this->addSql('DROP TABLE review');
    }
}
